import os

ACTIVATION_HOTKEY = "<alt>+k"
ICON_SIZE = 48
ICON_COLOR = "#4C4846"
ICON_IMAGE_PATH = "assets\Pikachu-PNG-Pic.png"

API_KEY = os.environ.get("GEMINI_API_KEY", "")

GEMINI_MODEL = "gemini-3.1-flash-lite"
GEMINI_API_VERSION = "v1beta"

MAX_OUTPUT_TOKENS = 200
THINKING_LEVEL = "low"

REQUEST_TIMEOUT_SECONDS = 8

MAX_UPLOAD_DIMENSION = 1280
MAX_UPLOAD_DIMENSION_OPTIONS = (800, 1280, 1920)

CURSOR_MARKER_RADIUS = 14
CURSOR_MARKER_COLOR = "#FF3B30"

GLIDE_DURATION_MS = 400
HIGHLIGHT_HOLD_MS = 1400
HIGHLIGHT_DIAMETER = 56
RETURN_HOLD_MS = 4000     

HISTORY_LIMIT = 3
